//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetailEjareMostaghelat
    {
        public int intId { get; set; }
        public Nullable<double> fltFloor { get; set; }
        public Nullable<double> fltZirbana { get; set; }
        public Nullable<byte> tintRoom { get; set; }
        public Nullable<short> sintTphone { get; set; }
        public Nullable<double> fltMetrajAnbari { get; set; }
        public Nullable<int> intIdDublex { get; set; }
        public Nullable<int> intIdKaf { get; set; }
        public Nullable<int> intIdService { get; set; }
        public Nullable<int> intIdKitchen { get; set; }
        public Nullable<int> intIdKabinet { get; set; }
        public Nullable<bool> blnShomineh { get; set; }
        public Nullable<bool> blnHayat { get; set; }
        public Nullable<double> fltMetrajBalcon { get; set; }
    
        public virtual tbl_BaseDublex tbl_BaseDublex { get; set; }
        public virtual tbl_BaseKabinet tbl_BaseKabinet { get; set; }
        public virtual tbl_BaseKaf tbl_BaseKaf { get; set; }
        public virtual tbl_BaseKitchen tbl_BaseKitchen { get; set; }
        public virtual tbl_BaseService tbl_BaseService { get; set; }
        public virtual tbl_EjareMostaghelat tbl_EjareMostaghelat { get; set; }
    }
}
