//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BaseNJavaz
    {
        public tbl_BaseNJavaz()
        {
            this.tbl_EjareMaghaze = new HashSet<tbl_EjareMaghaze>();
            this.tbl_SaleMaghaze = new HashSet<tbl_SaleMaghaze>();
        }
    
        public int intIdNJavaz { get; set; }
        public string chrNameNJavaz { get; set; }
    
        public virtual ICollection<tbl_EjareMaghaze> tbl_EjareMaghaze { get; set; }
        public virtual ICollection<tbl_SaleMaghaze> tbl_SaleMaghaze { get; set; }
    }
}
