//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EjareMostaghelat
    {
        public int intId { get; set; }
        public string chrDate { get; set; }
        public Nullable<bool> blnEslah { get; set; }
        public string chrDateEslah { get; set; }
        public string chrName { get; set; }
        public string chrPhone1 { get; set; }
        public string chrPhone2 { get; set; }
        public string chrPhone3 { get; set; }
        public Nullable<int> intIdAddress { get; set; }
        public string chrAddressMelk { get; set; }
        public string chrPelak { get; set; }
        public Nullable<double> fltGround { get; set; }
        public Nullable<double> fltBar { get; set; }
        public Nullable<int> intIdJusti { get; set; }
        public Nullable<double> fltFloors { get; set; }
        public Nullable<byte> tintUnit { get; set; }
        public Nullable<short> sintUnits { get; set; }
        public Nullable<bool> blnPark { get; set; }
        public Nullable<byte> tintOmr { get; set; }
        public Nullable<bool> blnAsansor { get; set; }
        public Nullable<bool> blnGaz { get; set; }
        public Nullable<int> intIdNama { get; set; }
        public Nullable<int> intIdHararat { get; set; }
        public Nullable<bool> blnSona { get; set; }
        public Nullable<int> intIdPool { get; set; }
        public Nullable<bool> blnJakuzi { get; set; }
        public Nullable<double> fltVadieh { get; set; }
        public Nullable<double> fltEjare { get; set; }
        public Nullable<bool> blnDoller { get; set; }
        public Nullable<bool> blnKhareji { get; set; }
        public Nullable<int> intIdKarbari { get; set; }
        public string chrMolahezat { get; set; }
        public Nullable<int> intIdMobleh { get; set; }
        public Nullable<int> intIdNBargh { get; set; }
        public Nullable<bool> blnIfon { get; set; }
        public Nullable<bool> blnRemoteDoor { get; set; }
        public Nullable<bool> blnSecurity { get; set; }
        public Nullable<int> number2 { get; set; }
        public Nullable<bool> blnIsPersonal { get; set; }
        public Nullable<int> intIdResidan { get; set; }
        public string chrTavasot { get; set; }
        public string chrVaredkonandeh { get; set; }
    
        public virtual tbl_BaseAddress tbl_BaseAddress { get; set; }
        public virtual tbl_BaseHararat tbl_BaseHararat { get; set; }
        public virtual tbl_BaseJusti tbl_BaseJusti { get; set; }
        public virtual tbl_BaseKarbari tbl_BaseKarbari { get; set; }
        public virtual tbl_BaseMobleh tbl_BaseMobleh { get; set; }
        public virtual tbl_BaseNama tbl_BaseNama { get; set; }
        public virtual tbl_BaseNBargh tbl_BaseNBargh { get; set; }
        public virtual tbl_BasePool tbl_BasePool { get; set; }
        public virtual tbl_BaseResidan tbl_BaseResidan { get; set; }
        public virtual tbl_DetailEjareMostaghelat tbl_DetailEjareMostaghelat { get; set; }
    }
}
