//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BaseOperator
    {
        public tbl_BaseOperator()
        {
            this.tbl_SaleMaghaze = new HashSet<tbl_SaleMaghaze>();
        }
    
        public int intIdOperator { get; set; }
        public string chrNameOperator { get; set; }
    
        public virtual ICollection<tbl_SaleMaghaze> tbl_SaleMaghaze { get; set; }
    }
}
