//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Credit = new HashSet<Credit>();
            this.Device = new HashSet<Device>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] CreateDate { get; set; }
    
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual ICollection<Device> Device { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
