//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vila
    {
        public int number1 { get; set; }
        public string date1 { get; set; }
        public Nullable<bool> eslah { get; set; }
        public string dateeslah { get; set; }
        public string region { get; set; }
        public string name1 { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string addressmelk { get; set; }
        public string pelak { get; set; }
        public Nullable<bool> kolangi { get; set; }
        public Nullable<double> ground { get; set; }
        public Nullable<double> bar { get; set; }
        public Nullable<double> eslahi { get; set; }
        public double zirbana { get; set; }
        public Nullable<byte> room { get; set; }
        public Nullable<short> tphone { get; set; }
        public Nullable<bool> gaz { get; set; }
        public string nbargh { get; set; }
        public string nama { get; set; }
        public string kaf { get; set; }
        public Nullable<bool> park { get; set; }
        public string kitchen { get; set; }
        public string kabinet { get; set; }
        public Nullable<bool> anbari { get; set; }
        public string service { get; set; }
        public Nullable<byte> omr { get; set; }
        public string hararat { get; set; }
        public Nullable<bool> shomineh { get; set; }
        public Nullable<bool> sona { get; set; }
        public Nullable<bool> hayat { get; set; }
        public Nullable<bool> pool { get; set; }
        public Nullable<bool> jakuzi { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> metri { get; set; }
        public string dublex { get; set; }
        public string karbari { get; set; }
        public string residan { get; set; }
        public string tavasot { get; set; }
        public string varedkonandeh { get; set; }
        public string molahezat { get; set; }
        public string justi { get; set; }
        public string sanad { get; set; }
        public string rname1 { get; set; }
        public Nullable<int> number2 { get; set; }
        public Nullable<bool> melkinfo { get; set; }
        public Nullable<bool> entmelkinfo { get; set; }
    }
}
