//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quantum.Amlak.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamin
    {
        public int number1 { get; set; }
        public string date1 { get; set; }
        public Nullable<bool> eslah { get; set; }
        public string dateeslah { get; set; }
        public string region { get; set; }
        public string name1 { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string addressmelk { get; set; }
        public string mahdoodeh { get; set; }
        public string justi { get; set; }
        public string zregion { get; set; }
        public Nullable<double> tarakom { get; set; }
        public Nullable<double> eslahi { get; set; }
        public Nullable<double> metraj { get; set; }
        public Nullable<bool> wall { get; set; }
        public string sanad { get; set; }
        public Nullable<double> bar { get; set; }
        public Nullable<bool> asfalt { get; set; }
        public Nullable<bool> ab { get; set; }
        public Nullable<bool> bargh { get; set; }
        public Nullable<double> tool { get; set; }
        public Nullable<bool> chaheab { get; set; }
        public Nullable<byte> fasele { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> metri { get; set; }
        public string molahezat { get; set; }
        public string residan { get; set; }
        public string tavasot { get; set; }
        public string varedkonandeh { get; set; }
        public string rname1 { get; set; }
        public Nullable<int> number2 { get; set; }
        public Nullable<bool> melkinfo { get; set; }
        public Nullable<bool> entmelkinfo { get; set; }
    }
}
